{
 "title": "SIGHUP Distribution Cluster Overview",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "services",
    "label": "services",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "node_role",
    "query": {
     "query": "label_values(kube_node_role{cluster=\"$cluster\"}, role)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_role{cluster=\"$cluster\", role=\"$node_role\"}, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"$cluster\", node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable{cluster=\"$cluster\", node=~\"$node\"}==0)"
    }
   ]
  },
  {
   "title": "Total Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{pod!=\"\", node=~\"$node\", namespace=~\"$namespace\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\", namespace=~\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{namespace=~\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(x509_cert_not_after)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Expired Certificates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((x509_cert_not_after - time()) / 86400) < bool 0)"
    }
   ]
  },
  {
   "title": "Certificates expiring within 7 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((x509_cert_not_after - time()) / 86400) < bool 7)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_unschedulable{cluster=\"$cluster\", node=~\"$node\"}!=0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\", namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container!=\"\",node=~\"$node\", namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Node Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage per container",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "max(container_memory_working_set_bytes{name!=\"\", node=~\"$node\", namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$node\", namespace=~\"$namespace\"}) by (pod)"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\"}) by (pod)"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
      },
      {
       "expr": "max(kube_pod_info) by (pod,namespace,node)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_spec_unschedulable{cluster=\"$cluster\", node=~\"$node\"}!=0) by (node) or sum(kube_node_spec_unschedulable{cluster=\"$cluster\", node=~\"$node\"}==0) by (node)"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daemon Sets",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$namespace\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_created{namespace=~\"$namespace\"}) - count(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "count(kube_deployment_created{namespace=~\"$namespace\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})",
       "legendFormat": "Succeeded"
      },
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase!=\"Running\", namespace=~\"$namespace\"} and kube_pod_status_phase{phase!=\"Succeeded\", namespace=~\"$namespace\"}) OR on() vector(0)",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\"} or kube_pod_status_phase{phase=\"Succeeded\", namespace=~\"$namespace\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Replica Sets",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_replicaset_created{namespace=~\"$namespace\"}) - count(kube_replicaset_status_ready_replicas{namespace=~\"$namespace\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "count(kube_replicaset_created{namespace=~\"$namespace\"})",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Stateful Sets",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_statefulset_created{namespace=~\"$namespace\"}) - count(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
       "legendFormat": "Failed"
      },
      {
       "expr": "count(kube_statefulset_created{namespace=~\"$namespace\"})",
       "legendFormat": "Running"
      }
     ]
    }
   ]
  },
  {
   "title": "Daemon Sets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_status_number_available{namespace=~\"$namespace\"}) by (namespace,daemonset)",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(kube_daemonset_status_desired_number_scheduled{namespace=~\"$namespace\"}) by (namespace,daemonset)",
       "legendFormat": "Desired"
      },
      {
       "expr": "sum(kube_daemonset_status_current_number_scheduled{namespace=~\"$namespace\"}) by (namespace,daemonset)",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(kube_daemonset_status_number_ready{namespace=~\"$namespace\"}) by (namespace,daemonset)",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(kube_daemonset_status_updated_number_scheduled{namespace=~\"$namespace\"}) by (namespace,daemonset)",
       "legendFormat": "Up-To-Date"
      },
      {
       "expr": "sum(kube_daemonset_status_number_unavailable{namespace=~\"$namespace\"}) by (namespace,daemonset)",
       "legendFormat": "Unavailable"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"}) by (namespace,deployment)",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_ready{namespace=~\"$namespace\"}) by (namespace,deployment)",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"}) by (namespace,deployment)",
       "legendFormat": "Up-To-Date"
      },
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable) by (namespace,deployment)",
       "legendFormat": "Unavailable"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"}) by (namespace, job, job_name)",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"}) by (namespace, job, job_name)",
       "legendFormat": "Succeeded"
      },
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"}) by (namespace, job, job_name)",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\"}) by (namespace, pod)",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Failed\", namespace=~\"$namespace\"}) by (namespace, pod)",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Pending\", namespace=~\"$namespace\"}) by (namespace, pod)",
       "legendFormat": "Pending"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\", namespace=~\"$namespace\"}) by (namespace, pod)",
       "legendFormat": "Succeeded"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Unknown\", namespace=~\"$namespace\"}) by (namespace, pod)",
       "legendFormat": "Unknown"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica Sets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_replicaset_status_replicas{namespace=~\"$namespace\"}) by (namespace, replicaset)",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(kube_replicaset_status_ready_replicas{namespace=~\"$namespace\"}) by (namespace, replicaset)",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(kube_replicaset_spec_replicas{namespace=~\"$namespace\"}) by (namespace, replicaset)",
       "legendFormat": "Desired"
      }
     ]
    }
   ]
  },
  {
   "title": "Stateful Sets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas_current{namespace=~\"$namespace\"}) by (namespace, statefulset)",
       "legendFormat": "Current"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}) by (namespace, statefulset)",
       "legendFormat": "Ready"
      },
      {
       "expr": "sum(kube_statefulset_replicas{namespace=~\"$namespace\"}) by (namespace, statefulset)",
       "legendFormat": "Desired"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_available) by (namespace, statefulset)",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_updated) by (namespace, statefulset)",
       "legendFormat": "Updated"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volume Claim",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\"${namespace}\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"}/1024/1024/1024)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"}/1024/1024/1024)"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"} * 100)"
      }
     ]
    }
   ]
  }
 ]
}