# Copyright (c) 2021 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: x509-certificate-exporter
  labels:
    app: x509-certificate-exporter
spec:
  selector:
    matchLabels:
      app: x509-certificate-exporter
  template:
    metadata:
      labels:
        app: x509-certificate-exporter
    spec:
      serviceAccountName: x509-certificate-exporter-node
      restartPolicy: Always
      containers:
        - name: x509-certificate-exporter
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 0
            runAsUser: 0
          image: docker.io/enix/x509-certificate-exporter
          imagePullPolicy: IfNotPresent
          args:
            - --listen-address=:9793
            - --trim-path-components=2
            - --max-cache-duration=300s
            - --watch-file=/var/lib/kubelet/pki/kubelet-client-current.pem
            - --watch-file=/var/lib/kubelet/pki/kubelet.crt
            - --watch-kubeconf=/etc/kubernetes/kubelet.conf
          ports:
            - name: metrics
              containerPort: 9793
          volumeMounts:
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
            - name: var-lib-kubelet-pki
              mountPath: /var/lib/kubelet/pki
              readOnly: true
      volumes:
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: var-lib-kubelet-pki
          hostPath:
            path: /var/lib/kubelet/pki
            type: Directory
