# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# WIP: This is an attempt to set the right values to get the same result as the
# kustomize patches and overlays we have in this repo.
# Please adjust as needed.
image:
  registry: registry.sighup.io/fury
grafana:
  # We create the ConfigMap manually because automatic creation generates a non-human-readable one-line resource.
  createDashboard: false

hostPathsExporter:
  daemonSets:
    data-plane:
      watchFiles:
        - /var/lib/kubelet/pki/kubelet.crt
        - /var/lib/kubelet/pki/kubelet-client-current.pem
      watchKubeconfFiles:
        - /etc/kubernetes/kubelet.conf
    control-plane:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
          add:
            - DAC_OVERRIDE
      watchFiles:
        # Common kubelet files
        - /var/lib/kubelet/pki/kubelet.crt
        - /var/lib/kubelet/pki/kubelet-client-current.pem
        # Control plane specific files
        - /etc/etcd/pki/apiserver-etcd-client.crt
        - /etc/etcd/pki/etcd/ca.crt
        - /etc/etcd/pki/etcd/healthcheck-client.crt
        - /etc/etcd/pki/etcd/peer.crt
        - /etc/etcd/pki/etcd/server.crt
        - /etc/kubernetes/pki/apiserver.crt
        - /etc/kubernetes/pki/ca.crt
        - /etc/kubernetes/pki/front-proxy-ca.crt
        - /etc/kubernetes/pki/front-proxy-client.crt
        - /etc/kubernetes/admin.conf
        - /etc/kubernetes/controller-manager.conf
        - /etc/kubernetes/scheduler.conf
      watchKubeconfFiles:
        # Common kubelet kubeconf file
        - /etc/kubernetes/kubelet.conf
        # Control plane specific files
        - /etc/kubernetes/admin.conf
        - /etc/kubernetes/super-admin.conf
        - /etc/kubernetes/controller-manager.conf
        - /etc/kubernetes/scheduler.conf
