[tasks.chart-version]
run = '''
helm repo add enix https://charts.enix.io
helm repo update
helm search repo enix/x509-certificate-exporter -l
'''

[tasks.upgrade]
usage = '''
arg "<chart_version>" help="x509 Exporter helm chart version"
'''
run = '''
echo "Using chart version ${usage_chart_version}"

rm -rf /tmp/x509-certificate-exporter
helm pull enix/x509-certificate-exporter --version "${usage_chart_version}" --untar --untardir /tmp
echo "Pulled helm chart ${usage_chart_version}"

helm lint /tmp/x509-certificate-exporter --values MAINTENANCE.values.yaml
echo "Helm lint done"

helm template x509-certificate-exporter /tmp/x509-certificate-exporter \
  --namespace monitoring \
  --values MAINTENANCE.values.yaml > deploy.yaml
echo "Built chart template in deploy.yaml"

mkdir -p config
wget -q "https://raw.githubusercontent.com/enix/x509-certificate-exporter/refs/tags/v${usage_chart_version}/chart/grafana-dashboards/x509-certificate-exporter.json" \
  -O config/x509-certificate-exporter.json
echo "Downloaded Grafana dashboard in config/x509-certificate-exporter.json"

yq -i '
  with(select(.kind == "PrometheusRule") | .metadata.labels;
    . = {"app": "x509-certificate-exporter", "prometheus": "k8s", "role": "alert-rules"}
  ),
  with(select(.kind != "PrometheusRule") | .metadata.labels;
    . = {"app": "x509-certificate-exporter"}
  )
' deploy.yaml
yq -i 'with(select(.spec.template.metadata.labels) | .spec.template.metadata.labels; . = {"app": "x509-certificate-exporter"})' deploy.yaml
yq -i 'with(select(.spec.selector.matchLabels) | .spec.selector.matchLabels; . = {"app": "x509-certificate-exporter"})' deploy.yaml
yq -i 'with(select(.kind == "Service") | .spec.selector; . = {"app": "x509-certificate-exporter"})' deploy.yaml
echo "Patched manifests in deploy.yaml"

mise run //:add-license
'''